### ISSUE TITLE
Unable to find a module

### ISSUE THREAD

**Issue by lars-w-pedersen** [Geta/geta-notfoundhandler#4]
When i try to go into episerver ui i get the following error:

An unhandled exception has occurred while executing the request.
System.ArgumentException: Unable to find a module by assembly 'Geta.NotFoundHandler.Optimizely, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' (Parameter 'moduleAssembly')
   at EPiServer.Shell.Paths.ToResource(Assembly moduleAssembly, String moduleRelativeResourcePath)
   at EPiServer.Shell.Paths.ToResource(Type typeInModuleAssembly, String moduleRelativeResourcePath)
   at Geta.NotFoundHandler.Optimizely.MenuProvider.GetMenuItems()

**Comment by lars-w-pedersen** [comment]
i also get this in the log:

2021-07-29 08:00:31.044 +02:00 [DBG] Looking for module in '~/EPiServer/Geta.NotFoundHandler.Optimizely'
2021-07-29 08:00:31.046 +02:00 [WRN] The modules finder couldn't find a directory at '~/EPiServer/Geta.NotFoundHandler.Optimizely'
2021-07-29 08:00:31.047 +02:00 [DBG] Looking for module in '/EPiServer/Geta.NotFoundHandler.Optimizely'
2021-07-29 08:00:31.047 +02:00 [WRN] The modules finder couldn't find a directory at '/EPiServer/Geta.NotFoundHandler.Optimizely'

**Comment by valdisiljuconoks** [comment]
Can you repro this with 1.0.0 version (not pre-release version)?

**Comment by cjsharp1** [comment]
This error occurs when you don't have the `services.AddOptimizelyNotFoundHandler()` in the ConfigureServices() method of Startup.cs.
