### ISSUE TITLE
SQL Errors at boottime

### ISSUE THREAD

**Issue by PierreYaksa** [Geta/geta-notfoundhandler#55]
Hello,

I have a .NET6 Alloy based project.

I upgraded _Geta-NotFoundHandler_ from the version 3.0.0 to the latest one 5.0.1 and I noticed few SQL errors when I launch the site. I seems it tries create an already existing SQL Table.

This is not blocking as it doesn't seem to have any side effect so far by I just wanted to shared the issue:

```
_fail: Geta.NotFoundHandler.Data.SqlDataExecutor[0]
      An error occurred in the ExecuteScalar method with the following sql: SELECT *
                       FROM INFORMATION_SCHEMA.TABLES
                       WHERE TABLE_SCHEMA = 'dbo'
                       AND  TABLE_NAME = '[dbo].[NotFoundHandler.RegexRedirects]'
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Geta.NotFoundHandler.Data.SqlDataExecutor.ExecuteScalar(String sqlCommand)_
```

```
_fail: Geta.NotFoundHandler.Data.SqlDataExecutor[0]
      An error occurred in the ExecuteSQL method with the following sql: CREATE TABLE [dbo].[NotFoundHandler.RegexRedirects] (
                                              [Id] [uniqueidentifier] NOT NULL,
                                              [OldUrlRegex] [nvarchar](2000) NOT NULL,
                                              [NewUrlFormat] [nvarchar](2000) NOT NULL,
                                              [OrderNumber] [int] NOT NULL,
                                              [TimeoutCount] [int] NOT NULL,
                                              [CreatedAt] [datetime] NOT NULL,
                                              [ModifiedAt] [datetime] NOT NULL,
                                              CONSTRAINT [PK_NotFoundHandlerRegexRedirects] PRIMARY KEY CLUSTERED ([Id] ASC) ON [PRIMARY]
                                              ) ON [PRIMARY]
      Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'NotFoundHandler.RegexRedirects' in the database.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
         at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
         at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
         at Geta.NotFoundHandler.Data.SqlDataExecutor.ExecuteNonQuery(String sqlCommand, IDbDataParameter[] parameters)_

```
Thank you and have a good day,

**Comment by marisks** [comment]
@PierreYaksa That's strange. It seems that on 3.0.0 your DB failed to upgrade, but the question is why it threw an exception when checking for an existing table.
I will take a look.
