### ISSUE TITLE
NullReferenceException on redirect

### ISSUE THREAD

**Issue by QuirijnLangedijk** [Geta/geta-notfoundhandler#63]
Hi,

After upgrading from V1.0.4 to V5.0.1, whenever I visit an non-existing link, instead of redirecting to /404, a NullReferenceException is thrown:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Geta.NotFoundHandler.Core.Redirects.CustomRedirectCollection.<>c.<FindInProviders>b__14_1(RewriteResult rewriteResult)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator'2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable'1 source, Boolean& found)
   at Geta.NotFoundHandler.Core.Redirects.CustomRedirectCollection.FindInProviders(String oldUrl)
   at Geta.NotFoundHandler.Core.Redirects.CustomRedirectCollection.Find(Uri urlNotFound)
   at Geta.NotFoundHandler.Core.RequestHandler.HandleRequest(Uri referer, Uri urlNotFound, CustomRedirect& foundRedirect)
   at Geta.NotFoundHandler.Core.RequestHandler.Handle(HttpContext context)
   at Geta.NotFoundHandler.Infrastructure.Initialization.NotFoundHandlerMiddleware.InvokeAsync(HttpContext context, RequestHandler requestHandler)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Web.Startup.<>c.<<Configure>b__4_0>d.MoveNext()`

Perhaps this is unrelated, but Ive noticed some of the added redirects have a redirect type of 0. When I visit one of these links, the same error is thrown. If I go into the database and change this to 301/302, the error dissapears, and the page is redirected correctly.

Has anything changed between V1.0.4 and V5.0.1 that I am also supposed to change in the code?

**Comment by marisks** [comment]
I don't know if something related has changed between these versions. 1.0.4 is quite old.

**Comment by QuirijnLangedijk** [comment]
Ive done some more trial and error, and it seems like custom redirecthandlers break this.
The INotFoundHandler interface used to be `string RewriteUrl(string url);` but is now `RewriteResult RewriteUrl(string url);`, so I updated the code to look like this: 
`        public RewriteResult RewriteUrl(string url)
        {
            if (url.Contains("/nl/en/expertise/topics/") ||
                url.Contains("/nl/nl/expertise/thema-s/") ||
                url.Contains("/be/en/expertise/topics/") ||
                url.Contains("/be/nl/expertise/topics/") ||
                url.Contains("/be/fr/expertise/topics/") ||
                url.Contains("/ch/en/expertise/topics/"))
            {
                var overviewPage = _pageHelper.LoadPageType<TopicOverviewPage>();
                return new RewriteResult(UrlHelpers.GetExternalUrl(overviewPage?.ContentLink, new CultureInfo("en")), RedirectType.Permanent);
            }

            return null;
        }`


Im guessing the return null causes the NullReferenceException, but Im not sure if this needs to be something else, since the documentation still has the old interface implementation

**Comment by marisks** [comment]
Yes, 'null' is not a valid result. Use `RewriteResult.Empty` instead.

P.S. Ok. We will have to update the documentation.

**Comment by QuirijnLangedijk** [comment]
Thanks, that works
