### ISSUE TITLE
SQL error for logging url suggestions

### ISSUE THREAD

**Issue by paalm** [Geta/geta-notfoundhandler#7]
I got this SQL error when logging url suggestions:

`Geta.NotFoundHandler.Data.SqlDataExecutor: Error: An error occurred in the ExecuteSQL method with the following sql: INSERT INTO [dbo].[NotFoundHandler.Suggestions]
                                    (Requested, OldUrl, Referer)
                                    VALUES
                                    (@requested, @oldurl, @referer)

System.ArgumentException: The SqlParameter is already contained by another SqlParameterCollection.
   at Microsoft.Data.SqlClient.SqlParameterCollection.Validate(Int32 index, Object value)
   at Microsoft.Data.SqlClient.SqlParameterCollection.Add(Object value)
   at Geta.NotFoundHandler.Data.SqlDataExecutor.CreateCommand(SqlConnection connection, String sqlCommand, IDbDataParameter[] parameters)
   at Geta.NotFoundHandler.Data.SqlDataExecutor.ExecuteNonQuery(String sqlCommand, IDbDataParameter[] parameters)`

**Comment by palle-mertz-isobar** [comment]
Ok I think 19 days was a long time to be open for such a breaker and simple fix, so I thought to my self why not make a first ever contribution to open source.
@valdisiljuconoks Do you think it would be possible to get the fix in asap and get it release to the nuget feed?

**Comment by valdisiljuconoks** [comment]
Awesome you took the courage! 😁🤘
Running internal review...
